name: Build Gradle project

on:
  workflow_call:
    inputs:
      os-name:
        required: true
        type: string
      java-name:
        required: true
        type: string
      java-distribution:
        required: true
        type: string

jobs:
  build-gradle-project:
    runs-on: ${{ inputs.os-name }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-name }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build